---
title: "CellMarker Genes for Over-Representation Analysis"
author: Jaclyn Taroni for the CCDL
date: 2021-06
output: 
  html_notebook: 
    toc: true
    toc_float: true
---

Adapted from [the `clusterProfiler` book section on Cell Markers](http://yulab-smu.top/clusterProfiler-book/chapter3.html#cell-marker), this notebook preps [CellMarker](http://bio-bigdata.hrbmu.edu.cn/CellMarker/) data for use in the ORA notebook.

## Set up

```{r}
library(tidyverse)
```
### Input

```{r}
hs_url <- "http://bio-bigdata.hrbmu.edu.cn/CellMarker/download/Human_cell_markers.txt"
mm_url <- "http://bio-bigdata.hrbmu.edu.cn/CellMarker/download/Mouse_cell_markers.txt"
```

### Output

```{r}
output_dir <- file.path("..", "gene-sets")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
```

Two tables: one for human, one for mouse

```{r}
hs_output <- file.path(output_dir, "CellMarker_cleaned_human_markers.tsv")
mm_output <- file.path(output_dir, "CellMarker_cleaned_mouse_markers.tsv")
```

### Custom function

```{r}
# Only to be used in this context! Avoid repeating code for both organisms
clean_marker_genes <- function(cell_marker_url) {
  
  cell_markers <- read_tsv(cell_marker_url) %>% 
    # Remove undefined tissue types
    filter(tissueType != "Undefined") %>%
    # For the gene set "name" we're going to create a single column that has
    # all of this information
    unite("CellMarker", tissueType, cancerType, cellName, sep = ", ") %>% 
    # Composite gene set name + gene symbols, which are comma separated
    select(CellMarker, geneSymbol)
  
  # Remove brackets from ambiguously mapped genes
  cell_markers <- cell_markers %>%
    mutate(gene_symbol = str_remove_all(geneSymbol, "[\\[\\]]")) %>%
    drop_na(gene_symbol) %>%
    select(-geneSymbol)
  
  # Tidy format required for clusterProfiler functions
  cell_markers_df <- cell_markers %>% 
    separate_rows(gene_symbol, sep = ", ") %>%
    rename(cell_marker = CellMarker) %>%
    filter(gene_symbol != "NA")
  
}
```


## _Homo sapiens_

```{r}
hs_cell_markers_df <- clean_marker_genes(hs_url)
head(hs_cell_markers_df)
```
```{r}
write_tsv(hs_cell_markers_df, hs_output)
```

## _Mus musculus_

```{r}
mm_cell_markers_df <- clean_marker_genes(mm_url)
write_tsv(mm_cell_markers_df, mm_output)
```

## Session Info

```{r}
sessionInfo()
```
