---
title: "R Notebook"
output: html_notebook
---

```{r}
library(AUCell)
library(GSEABase)
library(msigdbr)

suppressPackageStartupMessages({
  library(SingleCellExperiment)
})
```

# Set up gene sets

```{r show_species}
msigdbr_species()
```

MSigDB contains 8 different gene set collections.

    H: hallmark gene sets
    C1: positional gene sets
    C2: curated gene sets
    C3: motif gene sets
    C4: computational gene sets
    C5: GO gene sets
    C6: oncogenic signatures
    C7: immunologic signatures
    
EWS gene sets are in C2.

```{r}
ewing_gene_set_names <- c("ZHANG_TARGETS_OF_EWSR1_FLI1_FUSION",
                          "RIGGI_EWING_SARCOMA_PROGENITOR_UP")

ewing_gene_sets_df <- msigdbr(species = "Homo sapiens",
                              category = "C2",
                              subcategory = "CGP") |>
  dplyr::filter(gs_name %in% ewing_gene_set_names)

ewing_gene_set_collection <- ewing_gene_set_names |>
  purrr::map(
    \(gene_set_name) ewing_gene_sets_df |>
      dplyr::filter(gs_name == gene_set_name) |>
      dplyr::pull(ensembl_gene) |>
      GeneSet(setName = gene_set_name,
              geneIdType = ENSEMBLIdentifier())
  ) |>
  GeneSetCollection()



```



# Read in data

```{r}
sce <- readr::read_rds("data/ewing-sarcoma/processed/SCPCS000490/SCPCL000822_processed.rds")
```

```{r}
head(colData(sce))
```

```{r}
counts_matrix <- counts(sce) |>
  as("dgCMatrix")
```

```{r}
# Remove genes from gene sets if they are not in the SCE
ewing_gene_set_collection <- subsetGeneSets(ewing_gene_set_collection,
                                            rownames(counts_matrix))
```


```{r}
set.seed(2024)
cell_rankings <- AUCell_buildRankings(counts_matrix)
```

```{r}
cell_auc <- AUCell_calcAUC(ewing_gene_set_collection, cell_rankings)

```

```{r}
# Adapted from https://github.com/aertslab/AUCell/blob/91753b327a39dc7a4bbed46408ec2271c485f2f0/vignettes/AUCell.Rmd#L295-L316
zhang_gene_set_ranks <- cell_rankings[geneIds(ewing_gene_set_collection)[["ZHANG_TARGETS_OF_EWSR1_FLI1_FUSION"]], ]

positive_example_barcode <- "CTGAGCGGTCTTTATC"  # 1 
negative_example_barcode <- "AGATAGAGTCACAATC" # 7

par(mfrow=c(1,2))
set.seed(222)
aucMaxRank <- nrow(cell_rankings)*0.05
na <- sapply(c(1, 7), function(i){
  x <- sort(getRanking(zhang_gene_set_ranks[,i]))
  aucCurve <- cbind(c(0, x, nrow(cell_rankings)), c(0:length(x), length(x)))
  op <- par(mar=c(5, 6, 4, 2) + 0.5)
  plot(aucCurve, 
       type="s", col="darkblue", lwd=1, 
       xlab="Gene rank", ylab="# genes in the gene set", 
       xlim=c(0, aucMaxRank*2), ylim=c(0, nGenes(ewing_gene_set_collection[["ZHANG_TARGETS_OF_EWSR1_FLI1_FUSION"]])), 
       main="Recovery curve", 
       sub=paste("Cell:", colnames(zhang_gene_set_ranks)[i]))
  aucShade <- aucCurve[which(aucCurve[,1] < aucMaxRank),]
  aucShade <- rbind(aucShade, c(aucMaxRank, nrow(aucShade)))
  aucShade[,1] <-  aucShade[,1]-1
  aucShade <- rbind(aucShade, c(max(aucShade),0))
  polygon(aucShade, col="#0066aa40", border=FALSE)
  
  abline(v=aucMaxRank, lty=2)
  text(aucMaxRank-50, 5, "AUC")
})

```


```{r}
auc_assignments <- AUCell_exploreThresholds(cell_auc, 
                                            plotHist = FALSE, 
                                            assignCells = TRUE)
```

```{r}
auc_df <- cell_auc@assays@data$AUC |> 
  as.data.frame() |>
  tibble::rownames_to_column("geneset") |>
  tidyr::pivot_longer(!geneset, 
                      names_to = "barcodes",
                      values_to = "auc") |>
  dplyr::select(barcodes, geneset, auc) |>
  dplyr::mutate(
    assigned = dplyr::case_when(
      geneset == ewing_gene_set_names[1] & barcodes %in% auc_assignments[[ewing_gene_set_names[1]]]$assignment ~ TRUE,
      geneset == ewing_gene_set_names[2] & barcodes %in% auc_assignments[[ewing_gene_set_names[2]]]$assignment ~ TRUE,
      .default = FALSE
    )
  )
```

```{r}
auc_threshold_df <- data.frame(
  geneset = ewing_gene_set_names,
  threshold = c(auc_assignments[[ewing_gene_set_names[1]]]$aucThr$selected, 
                auc_assignments[[ewing_gene_set_names[2]]]$aucThr$selected)
)

auc_df |>
  ggplot2::ggplot(
    ggplot2::aes(
      x = auc,
      color = assigned,
      fill = assigned,
    )
  ) +
  ggplot2::geom_density(alpha = 0.2) +
  ggplot2::geom_vline(data = auc_threshold_df,
                      mapping = ggplot2::aes(xintercept = threshold),
                      lty = 2) +
  ggplot2::facet_grid(cols = ggplot2::vars(geneset)) +
  ggplot2::theme_bw()
```

```{r}
auc_coldata_df <- cell_auc@assays@data$AUC |>
  t() |>
  as.data.frame() |>
  tibble::rownames_to_column("barcodes") |>
  dplyr::rename(zhang_auc = ewing_gene_set_names[1],
                riggi_auc = ewing_gene_set_names[2])
```


```{r}
coldata_df <- colData(sce) |>
  as.data.frame() |>
  dplyr::left_join(
    auc_coldata_df,
    by = "barcodes"
  )

colData(sce) <- DataFrame(
  coldata_df,
  row.names = colData(sce)$barcodes
)
```

```{r}
scater::plotUMAP(sce, colour_by = "zhang_auc")
```

```{r}
scater::plotUMAP(sce, colour_by = "riggi_auc")
```

