# The main directory where processed files will be stored
base_dir: /shared/data/training-modules/scRNA-seq-advanced/data/rms

# Libraries to process for the both the integration and differential gene expression modules
libraries: 
  - SCPCL000478
  - SCPCL000479
  - SCPCL000480
  - SCPCL000481
  - SCPCL000482
  - SCPCL000483
  - SCPCL000484
  - SCPCL000488
  - SCPCL000491
  - SCPCL000495
  - SCPCL000498
  - SCPCL000502
  - SCPCL000516
  - SCPCL000492
  - SCPCL000510
  
de_instruction_libraries:
  - SCPCL000478
  - SCPCL000479
  - SCPCL000480
  - SCPCL000481
  - SCPCL000482
  - SCPCL000483
  - SCPCL000484
  - SCPCL000488
  - SCPCL000491
  - SCPCL000495
  - SCPCL000498

de_exercise_libraries:
  - SCPCL000481
  - SCPCL000502
  - SCPCL000516
  - SCPCL000488
  - SCPCL000492
  - SCPCL000510


# Celltypes TSV file
celltypes_file: /shared/data/training-modules/scRNA-seq-advanced/data/rms/annotations/celltypes.tsv
