base_dir: ../../data/crc-hd/

# URLs for downloading original dataset and annotations from 10x
url_visium: https://cf.10xgenomics.com/samples/spatial-exp/4.1.0/Visium_HD_6p5mm_Human_Colon_Cancer/Visium_HD_6p5mm_Human_Colon_Cancer_segmented_outputs.tar.gz
url_single_cell: https://cf.10xgenomics.com/samples/cell-exp/8.0.0/HumanColonCancer_Flex_Multiplex/HumanColonCancer_Flex_Multiplex_count_filtered_feature_bc_matrix.tar.gz

# Output files
output_normalized_spe: crc_hd_normalized_spe.rds
output_normalized_sce: crc_single_cell_normalized_sce.rds
