configfile: "config.yaml"
outdir = config["base_dir"]

rule target:
  input:
    os.path.join(outdir, "processed")


rule prepare_muraro:
  output:
    directory(os.path.join(outdir, "processed"))
  log:
    "logs/muraro_setup.log"
  shell:
    """
      Rscript muraro_setup.R \
        --outdir "{output}" \
        >& {log}
    """
