# The main directory where files will be stored
base_dir: /shared/data/training-modules/RNA-seq
# salmon index file location
salmon_index: /shared/data/reference/refgenie/hg38_cdna/salmon_index/short/

# dataset name for organization & high level labeling 
dataset: gastric-cancer
# ids and run list for BioProject PRJNA178120
GSE: GSE41476
SRP: SRP016059
SRRs: 
  - SRR585570
  - SRR585571
  - SRR585572
  - SRR585573
  - SRR585574
  - SRR585575
  - SRR585576
  - SRR585577


