---
title: "Importing, processing, and exploring Visium data"
author: Data Lab for ALSF
date: 2026
output:
  html_notebook:
    toc: true
    toc_float: true
---

## Objectives

- Read Visium data into R
- Filter to spots overlapping tissue
- Calculate quality control measures on spatial transcriptomic data
- Remove likely low-quality spots with `SpotSweeper()`
- Normalize expression data across spots
- Visualize spatial transcriptomic data 

## Introduction

In this notebook, we'll learn some basic import, processing, and visualization of a Visium data set, starting with the Space Ranger output. 

The data we'll use in this notebook is from an anaplastic Wilms Tumor sample in the [Single-cell Pediatric Cancer Atlas](https://scpca.alexslemonade.org/projects/SCPCP000006).
This sample was processed using first-generation 3' Visium technology, and it was quantified with `Space ranger 1.3.1`.


## Session info

To conclude, we'll run the `sessionInfo()` command to print out exactly what system setting and R package versions were used to run this code.

```{r}
sessionInfo()
```

