# The main directory where files will be stored; use v1 to distinguish in case of other CRC datasets incoming
sample_dir: ../../data/crc-v1/

# Reference directory
ref_dir: ../../data/reference/

# URLs for downloading original dataset from 10x - need both the filtered matrix and the spatial folders
url_filtered: https://cf.10xgenomics.com/samples/spatial-exp/1.2.0/Parent_Visium_Human_ColorectalCancer/Parent_Visium_Human_ColorectalCancer_filtered_feature_bc_matrix.tar.gz
url_spatial: https://cf.10xgenomics.com/samples/spatial-exp/1.2.0/Parent_Visium_Human_ColorectalCancer/Parent_Visium_Human_ColorectalCancer_spatial.tar.gz

# Output files to create
output_spe: crc_normalized_spe.rds
