# Workflow for preparing the CRC Visium V1 dataset

from pathlib import Path

configfile: "config.yaml"

sample_dir      = Path(config["sample_dir"])
ref_dir         = Path(config["ref_dir"])
spaceranger_dir = sample_dir / "spaceranger"
normalized_dir  = sample_dir / "normalized"
mito_genes_file = ref_dir / "hs_mitochondrial_genes.tsv"
spe_file        = normalized_dir / config["output_spe"]

rule targets:
    input:
        spe_file

rule download_spatial:
    output:
        directory(spaceranger_dir / "filtered_feature_bc_matrix"),
        directory(spaceranger_dir / "spatial"),
    params:
        url_filtered = config["url_filtered"],
        url_spatial = config["url_spatial"]
    shell:
        """
        mkdir -p {spaceranger_dir}/filtered_feature_bc_matrix
        mkdir {spaceranger_dir}/spatial

        curl -L {params.url_filtered} | tar xz --strip-components=1 -C {spaceranger_dir}/filtered_feature_bc_matrix
        curl -L {params.url_spatial} | tar xz --strip-components=1 -C {spaceranger_dir}/spatial
        """ 

# import SPE, filter, normalize, and export rds as preparation for the 
# spatial clustering exercise notebook
rule prepare_sce:
    input:
        filtered_matrix = spaceranger_dir / "filtered_feature_bc_matrix",
        spatial         = spaceranger_dir / "spatial",
        mito_genes_file = mito_genes_file,
    output:
        spe_file
    params:
        notebook  = "prepare-crc-v1-data.Rmd",
    shell:
        """
        Rscript -e "
          rmarkdown::render(
            '{params.notebook}',
            params = list(
              filtered_matrix = '{input.filtered_matrix}',
              spatial_dir     = '{input.spatial}',
              mito_genes_file = '{input.mito_genes_file}',
              output_rds      = '{output}'
            ),
            output_file = fs::file_temp()
          )
        "
        """
