# The main directory where processed files will be stored
base_dir: /shared/data/training-modules/scRNA-seq-advanced/data/SCPCP000005-samples

# Libraries to process
libraries: ["SCPCL000478", "SCPCL000479", "SCPCL000480", "SCPCL000481"]

# Celltypes TSV file
celltypes_file: /shared/data/training-modules/scRNA-seq-advanced/data/SCPCP000005-samples/annotations/celltypes.tsv
