# The main directory where processed files will be stored
base_dir: /home/ccdl/stephanie/training-modules/scRNA-seq-advanced/setup/SCPCP000005-samples
#/shared/data/training-modules/scRNA-seq-advanced/data/SCPCP000005-samples

# Directory with pre-processed files; Original downloads should live here.
raw_dir: /home/ccdl/stephanie/training-modules/scRNA-seq-advanced/setup/SCPCP000005-samples/raw
#/shared/data/training-modules/scRNA-seq-advanced/data/SCPCP000005-samples/raw

# The notebook that prepares the data to be saved into `base_dir`
setup_notebook: /home/ccdl/stephanie/training-modules/scRNA-seq-advanced/setup/integration_setup.Rmd

# Libraries to download
libraries: ["SCPCL000478", "SCPCL000479", "SCPCL000480", "SCPCL000481"]

#url: maybe a TBD S3 bucket if anything?

