# Workflow for downloading and preprocessing SCPCP000005 data used for integration
configfile: "config.yaml"
workdir: config["base_dir"]

rule target:
    input:
        expand(os.path.join({library}.rds"),
               library = config["libraries"])

rule download_libraries:
  output:
    expand(os.path.join({library}_filtered.rds"),
               library = config["libraries"])
  shell:
    # curl from bucket? kill this rule?


rule prepare_libraries:
  output:
    expand(os.path.join({library}.rds"),
               library = config["libraries"])
  shell:
    """
      Rscript -e 'rmarkdown::render({config[setup_notebook]}'
    """