# Workflow for preprocessing SCPCP000005 data used for integration instruction
# Raw files are expected to be present in the `config[raw_dir]` directory

configfile: "config.yaml"
workdir: config["base_dir"]

rule target:
  input:
    expand(os.path.join(config['base_dir'], "{library}.rds"),
           library = config["libraries"])

rule prepare_libraries:
  output:
    expand(os.path.join(config['base_dir'], "{library}.rds"),
           library = config["libraries"])
  shell:
    """
    Rscript -e "rmarkdown::render('{config[setup_notebook]}', \
                        clean = TRUE,
                        params = list(setup_only = TRUE, \
                                      input_sce_path = '{config[raw_dir]}', \
                                      output_sce_path = '{config[base_dir]}')
                )"
    """
