# The main directory where files will be stored
base_dir: /shared/data/training-data/darmanis

GSE: GSE84465
SRP: SRP079058

salmon_index: /shared/data/reference/refgenie/hg38_cdna/salmon_index/short/short/
