# Workflow for downloading and preprocessing smartseq scRNA data
configfile: "config.yaml"

import pandas as pd

rule all:
    input:
        "sample_list.tsv"

checkpoint sample_list:
    output:
        "sample_list.tsv"
    shell:
        "Rscript get_srp_table.R"
        " --srp {config[SRP]}"
        " --outfile {output}"
        " --paired"


def sample_fastqc(wildcards):
    """
    Use the sample list file to generate the full fastqc file list
    """
    with open(checkpoints.sample_list.get(**wildcards).output) as f:
        fastqs = [line.rstrip() for line in f]
    return expand("{config.base_dir}/fastqc_reports/{fq}_fastqc.html",
        fq=fastqs)