base_dir: ../../data/ovarian-carcinoma/

# Reference directory
ref_dir: ../../data/reference/

# URLs for downloading original dataset from 10x
url_filtered: https://cf.10xgenomics.com/samples/spatial-exp/2.0.0/CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma/CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_filtered_feature_bc_matrix.tar.gz
url_spatial: https://cf.10xgenomics.com/samples/spatial-exp/2.0.0/CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma/CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_spatial.tar.gz
url_probes: https://cf.10xgenomics.com/supp/spatial-exp/probeset/Visium_Human_Transcriptome_Probe_Set_v2.0_GRCh38-2020-A.csv

# base URL for downloading reference files from GEO
base_url_geo: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE189nnn/GSE189955/suppl

# Output (and intermediate) reference files
ref_raw_counts: GSE189955_RNA_Count_matrix.csv.gz
ref_raw_metadata: GSE189955_RNA_meta_data.csv.gz
output_ref_rds: GSE189955_ovarian_ref.rds
