# Workflow for downloading Glioblastoma data from 10X
configfile: "config.yaml"
outdir = config["base_dir"]

rule targets:
  input:
   os.path.join(outdir, "raw", "glioblastoma_raw_matrix.h5")
  
rule download_raw:
  output:
    os.path.join(outdir, "raw", "glioblastoma_raw_matrix.h5")
  shell:
    "curl -L {config[url]} -o {output}" 

    
