# Workflow for downloading Glioblastoma data from 10X
configfile: "config.yaml"
outdir = config["base_dir"]

rule targets:
  input:
   os.path.join(outdir, "raw_feature_bc_matrix")
  
rule download_raw:
  output:
    directory(os.path.join(outdir, "raw_feature_bc_matrix"))
  shell:
    "curl -L {config[url]} | tar xz -C {outdir}" 

    
