# The main directory where files will be stored
base_dir: /shared/data/training-data/tabula-muris
# The location of the metadata
metadata_url: https://czbiohub-tabula-muris.s3.us-east-1.amazonaws.com/TM_droplet_metadata.csv

s3_url: s3://czbiohub-tabula-muris/10x_bam_files

salmon_index: /shared/data/reference/refgenie/mm10_cdna/salmon_index/short/short/
tx2gene: /shared/data/reference/tx2gene/mm_ensdb95_tx2gene.tsv

run_ids:
  - 10X_P4_0
  - 10X_P4_1
  - 10X_P4_2
  - 10X_P4_3
  - 10X_P4_4
  - 10X_P4_5
  - 10X_P4_6
  - 10X_P4_7
  - 10X_P7_0
  - 10X_P7_11
  - 10X_P7_12
  - 10X_P7_13
  - 10X_P7_14
  - 10X_P7_15
  - 10X_P7_2
  - 10X_P7_3
