# The main directory where files will be stored
base_dir: ../../data/osteo/

# Reference directory
ref_dir: ../../data/reference/

# sample name for path creation
sample_id: GSM8478586

# URL for downloading original dataset from GEO
geo_url: https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM8478nnn/GSM8478586/suppl/GSM8478586_SP0001.tar.gz

# URL for downloading OsteoCAR mouse mets reference
osteo_ref_url: https://api.figshare.com/v2/file/download/60882436


# Output files to create
output_osteo_spe: osteo_normalized_spe.rds
output_osteo_ref: mm_mets_osteo_ref.rds
output_osteo_ref_raw: mm_mets_osteo_ref_raw.qs
