# The main directory where files will be stored
base_dir: /shared/data/training-modules/spatial/data/osteo

# URL for downloading from GEO
url: https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM8478nnn/GSM8478586/suppl/GSM8478586%5FSP0001%2Etar%2Egz

# Mito genes file used for processing
mito_genes_file: /shared/data/training-modules/spatial/data/reference/hs_mitochondrial_genes.tsv

# Output file to create
output_rds: osteo_normalized_spe.rds
