# Workflow for preparing the GSM8478586 osteosarcoma dataset
from pathlib import Path

configfile: "config.yaml"

base_dir        = Path(config["base_dir"])
sample_dir      = base_dir / config["sample_id"]
spaceranger_dir = sample_dir / "spaceranger"
normalized_dir  = sample_dir / "normalized"
ref_dir         = base_dir / "reference"

rule targets:
    input:
        normalized_dir / config["output_rds"],
        ref_dir / config["output_osteo_ref"]

rule download_spatial:
    output:
        directory(spaceranger_dir / "filtered_feature_bc_matrix"),
        directory(spaceranger_dir / "spatial"),
    params:
        geo_url = config["geo_url"]
    shell:
        "curl -L {params.geo_url} | tar xz --strip-components=1 -C {spaceranger_dir}"

# import as SPE, filter, normalize, and export rds as preparation for the spatial clustering notebook
rule prepare_sce:
    input:
        filtered_matrix = spaceranger_dir / "filtered_feature_bc_matrix",
        spatial         = spaceranger_dir / "spatial",
        mito_genes_file = config["mito_genes_file"],
    output:
        normalized_dir / config["output_rds"]
    params:
        notebook = "prepare-osteo-data.Rmd"
    shell:
        """
        Rscript -e "
          rmarkdown::render(
            '{params.notebook}',
            params = list(
              filtered_matrix = '{input.filtered_matrix}',
              spatial_dir     = '{input.spatial}',
              mito_genes_file = '{input.mito_genes_file}',
              output_rds      = '{output}'
            ),
            output_file = fs::file_temp()
          )
        "
        """

rule download_osteo_ref:
    output:
        temp("mm_mets_osteo_ref_raw.qs")
    params:
        osteo_ref_url = config["osteo_ref_url"]
    shell:
        "curl -Lo {output} {params.osteo_ref_url}"

rule reformat_osteo_ref:
    input:
        osteo_ref = "mm_mets_osteo_ref_raw.qs", # doesn't need temp()
        spe       = normalized_dir / config["output_rds"]
    output:
        ref_dir / config["output_osteo_ref"]
    params:
        script = "reformat-osteo-ref.R"
    shell:
        """
        Rscript {params.script} \
            --input_osteo_ref {input.osteo_ref} \
            --output_osteo_ref {output} \
            --spe {input.spe}
        """
