# Workflow for preparing the GSM8478586 osteosarcoma dataset
configfile: "config.yaml"
sample_dir = os.path.join(config["base_dir"], config["sample_id"])

rule targets:
  input:
    os.path.join(sample_dir, "normalized", config["output_rds"])

rule download_spatial:
  output:
    directory(os.path.join(sample_dir, "filtered_feature_bc_matrix")),
    directory(os.path.join(sample_dir, "spatial")),
  params:
    url = config["url"]
  shell:
    "curl -L {params.url} | tar xz --strip-components=1 -C {sample_dir}"


# import as SPE, filter, normalize, and export rds as preparation for the spatial clustering notebook
rule prepare_sce:
  input:
    filtered_matrix = os.path.join(sample_dir, "filtered_feature_bc_matrix"),
    spatial         = os.path.join(sample_dir, "spatial"),
    mito_genes_file = config["mito_genes_file"],
  output:
    os.path.join(sample_dir, "normalized", config["output_rds"])
  params:
    notebook = "prepare-osteo-data.Rmd"
  shell:
    """
    Rscript -e "
      rmarkdown::render(
        '{params.notebook}',
        params = list(
          filtered_matrix = '{input.filtered_matrix}',
          spatial_dir     = '{input.spatial}',
          mito_genes_file = '{input.mito_genes_file}',
          output_rds      = '{output}'
        ),
        output_file = fs::file_temp()
      )
    "
    """
