# Workflow for preparing the GSM8478586 osteosarcoma dataset
configfile: "config.yaml"
base_dir = config["base_dir"]

rule targets:
  input:
    os.path.join(base_dir, "normalized", config["output_rds"])

rule download_spatial:
  output:
    directory(os.path.join(base_dir, "outs", "filtered_feature_bc_matrix")),
    directory(os.path.join(base_dir, "outs", "spatial")),
  params:
    url = config["url"]
  shell:
    "curl -L {params.url} | tar xz --strip-components=1 -C {base_dir}/outs"


# filter and normalize the SPE as preparation for the spatial clustering notebook
rule normalize_sce:
  input:
    filtered_matrix = os.path.join(base_dir, "outs", "filtered_feature_bc_matrix"),
    spatial         = os.path.join(base_dir, "outs", "spatial"),
    mito_genes_file = config["mito_genes_file"],
  output:
    os.path.join(base_dir, "normalized", config["output_rds"])
  params:
    notebook = "prepare-osteo-data.Rmd"
  shell:
    """
    Rscript -e "
      rmarkdown::render(
        '{params.notebook}',
        params = list(
          filtered_matrix = '{input.filtered_matrix}',
          spatial_dir     = '{input.spatial}',
          mito_genes_file = '{input.mito_genes_file}',
          output_rds      = '{output}'
        ),
        output_file = fs::file_temp()
      )
    "
    """
