base_dir: ../../data/brca-xenium/

# URLs for downloading original dataset and annotations from 10x
url_xenium: https://cf.10xgenomics.com/samples/xenium/1.0.1/Xenium_FFPE_Human_Breast_Cancer_Rep1/Xenium_FFPE_Human_Breast_Cancer_Rep1_outs.zip
url_annotations: https://cdn.10xgenomics.com/raw/upload/v1695234604/Xenium%20Preview%20Data/Cell_Barcode_Type_Matrices.xlsx

# Output files
output_annotations_tsv: Janesick_annotations.tsv
