# Workflow for downloading and preprocessing PBMC data
configfile: "config.yaml"
workdir: config["base_dir"]

rule targets:
  input:
   "raw_feature_bc_matrix"
  
rule download_raw:
  output:
    directory("raw_feature_bc_matrix")
  shell:
    "curl -L {config[url]} | tar xz" 
